name: backend

services:
  postgres:
    container_name: backend_postgres
    environment:
      POSTGRES_SERVER: "postgres"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgres:16.3
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
  docs:
    command: fastapi run app/main.py --host 0.0.0.0
    container_name: backend_app
    environment:
      DEBUG: True
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - 8000

networks:
  default:
    name: "docs"
    external: true

volumes:
  postgres:
    name: backend_postgres
