"""auth

Revision ID: 46ebad8f1f0f
Revises: 
Create Date: 2024-12-10 10:54:50.669725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '46ebad8f1f0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('patronymic', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False, default=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, default=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auth_group_permission',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id', 'group_id')
    )
    op.create_table('auth_user_group',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('auth_user_permission',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.execute("INSERT INTO auth_user (email,password,name,surname,patronymic,active,is_superuser) VALUES ('admin', '$2b$12$6UqdBH8i/IR.PV9.yc/OkOGx9UNmKqR7GYgsofpYGGngdcswdDcPW', 'admin', 'admin', 'admin', TRUE, TRUE);")
    op.execute("INSERT INTO auth_group (name) VALUES ('Уровень1');")
    op.execute("INSERT INTO auth_group (name) VALUES ('Уровень2');")
    op.execute("INSERT INTO auth_group (name) VALUES ('Уровень3');")
    op.execute("INSERT INTO auth_permission (name) VALUES ('doc:read');")
    op.execute("INSERT INTO auth_group_permission (permission_id,group_id) VALUES (1,1);")
    op.execute("INSERT INTO auth_group_permission (permission_id,group_id) VALUES (1,2);")
    op.execute("INSERT INTO auth_group_permission (permission_id,group_id) VALUES (1,3);")
    op.execute("INSERT INTO auth_permission (name) VALUES ('report:create');")
    op.execute("INSERT INTO auth_group_permission (permission_id,group_id) VALUES (2,1);")
    op.execute("INSERT INTO auth_group_permission (permission_id,group_id) VALUES (2,2);")
    op.execute("INSERT INTO auth_permission (name) VALUES ('activity:read');")
    op.execute("INSERT INTO auth_group_permission (permission_id,group_id) VALUES (3,1);")
    op.execute("INSERT INTO auth_group_permission (permission_id,group_id) VALUES (3,2);")
    op.execute("INSERT INTO auth_group_permission (permission_id,group_id) VALUES (3,3);")
    op.execute("INSERT INTO auth_permission (name) VALUES ('doc:update');")
    op.execute("INSERT INTO auth_group_permission (permission_id,group_id) VALUES (4,3);")
    op.execute("INSERT INTO auth_permission (name) VALUES ('doc:create');")
    op.execute("INSERT INTO auth_group_permission (permission_id,group_id) VALUES (5,3);")
    op.execute("INSERT INTO auth_permission (name) VALUES ('doc.comment:create');")
    op.execute("INSERT INTO auth_group_permission (permission_id,group_id) VALUES (6,2);")
    op.execute("INSERT INTO auth_group_permission (permission_id,group_id) VALUES (6,3);")
    op.execute("INSERT INTO auth_permission (name) VALUES ('doc.status:create');")
    op.execute("INSERT INTO auth_group_permission (permission_id,group_id) VALUES (7,2);")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_user_permission')
    op.drop_table('auth_user_group')
    op.drop_table('auth_group_permission')
    op.drop_table('auth_user')
    op.drop_table('auth_permission')
    op.drop_table('auth_group')
    # ### end Alembic commands ###
